M48
; DRILL file {KiCad (5.99.0-13123-g97e9348ee1)} date 2021 December 06, Monday 14:29:13
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2021-12-06T14:29:13+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(5.99.0-13123-g97e9348ee1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X3.6657Y-2.4704
X3.8933Y-2.4704
T0
M30
